// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokRichtext, StoryblokMultilink } from '../storyblok.d.ts';
export interface Expandable {
    expandButtonText?: string;
    contentExpand?: StoryblokRichtext;
    component: 'expandable';
    _uid: string;
}

export interface Gig {
    title: string;
    date: string;
    entryTime?: string;
    placeShort: string;
    place: string;
    price?: string;
    linkTickets?: string;
    description?: StoryblokRichtext;
    component: 'gig';
    _uid: string;
}

export interface Gigs {
    list?: Gig[];
    component: 'gigs';
    _uid: string;
}

export interface GigsReference {
    showOnlyFuture?: boolean;
    reference?: ISbStoryData<Gigs> | string;
    component: 'gigs_reference';
    _uid: string;
}

export interface Image {
    image: StoryblokAsset;
    component: 'image';
    _uid: string;
}

export interface ImageSlider {
    images: Image[];
    component: 'image_slider';
    _uid: string;
}

export interface Page {
    id?: string;
    title: string;
    auditionText?: StoryblokRichtext;
    auditionLink?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
    showAuditionLink?: boolean;
    newsletterText?: StoryblokRichtext;
    contactText?: StoryblokRichtext;
    description?: string;
    body?: Section[];
    component: 'page';
    _uid: string;
}

export interface Section {
    id: string;
    title: string;
    gigs?: GigsReference[];
    content?: StoryblokRichtext;
    component: 'section';
    _uid: string;
}

export interface YoutubeVideo {
    title: string;
    code: string;
    component: 'youtube_video';
    _uid: string;
}

export interface YoutubeVideoSlider {
    videos: YoutubeVideo[];
    component: 'youtube_video_slider';
    _uid: string;
}

export type ContentType = Gigs | Page;
