inputs:
  CACHIX_AUTH_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24

    - name: Setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: gerschtli
        authToken: ${{ inputs.CACHIX_AUTH_TOKEN }}

    - name: Build dev shell
      shell: bash
      run: nix develop --profile profile && rm profile
