version: '3.1'

services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - website-postgres-state:/var/lib/postgresql/data

volumes:
  website-postgres-state:
