name: Keep supabase active
on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: curl --fail-with-body -sSlI https://www.popchor-koeln.de/gaestebuch
